project:
  output-dir: _outputs/html

website:
  title: "IASI Journey"
  sidebar:
    style: docked
    search: true
    contents: auto

format:
  html:
    toc: true
    number-sections: false
    include-before-body: resources/html/ants-banner.html
    theme:
      - cosmo
      - resources/css/iasi.scss
