project:
  type: book

  resources:
    - resources/**

profile:
  default: html
  group:
    - [html, pdf]
    
metadata-files:
  - _book-structure.yml

lang: es

book:
  title: "IASI Journey"
  author: "Javier G. Grandez"
